baseURL: "https://naadiyaar.com/"
languageCode: 'en-us'
title: 'Naadiyaar'
theme: PaperMod
paginate: 25

params:
    homeInfoParams:
        Title: Welcome my cyber sanctuary
        Content: >
          I find great delight in expressing my thoughts through writing.

          - In the grand tapestry of life, we all stumble and falter, including me and the posts I share.

          - Journaling my technical life and exploring simple ideas is what I'm doing here.
          
          - **hope you enjoy :)**

    socialIcons:
      - name: email
        url: mailto:naadiyaar@protonmail.com
      # - name: xmpp
      #   url: xmpp:naadiyaar@conversations.im
      - name: matrix
        url: https://matrix.to/#/@naadiyaar:fedora.im
      - name: mastodon
        url: https://fosstodon.org/@naadiyaar
      - name: codeberg
        url: https://codeberg.org/Naadiyaar
      - name: rss
        url: http://naadiyaar.com/index.xml

    ShowCodeCopyButtons: true

menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
outputs:
  home:
      - HTML
      - RSS
      - JSON
